// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtoQH6-MWjtaQ1RXHbx_66AxOjLqtSh08',
    appId: '1:1054015406612:web:6b4666162ab70ec034dd01',
    messagingSenderId: '1054015406612',
    projectId: 'veterinary-application-bfb4e',
    authDomain: 'veterinary-application-bfb4e.firebaseapp.com',
    databaseURL: 'https://veterinary-application-bfb4e-default-rtdb.firebaseio.com',
    storageBucket: 'veterinary-application-bfb4e.appspot.com',
    measurementId: 'G-EC4TYM4BRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Db1MTk0vXi_KR-kIxC48cvsMjslzLvs',
    appId: '1:1054015406612:android:2bfa13d4f088a1d534dd01',
    messagingSenderId: '1054015406612',
    projectId: 'veterinary-application-bfb4e',
    databaseURL: 'https://veterinary-application-bfb4e-default-rtdb.firebaseio.com',
    storageBucket: 'veterinary-application-bfb4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxzKsW3-XWahj_Ba8pq506BaI-jEQj3NQ',
    appId: '1:1054015406612:ios:580775f60e7e206b34dd01',
    messagingSenderId: '1054015406612',
    projectId: 'veterinary-application-bfb4e',
    databaseURL: 'https://veterinary-application-bfb4e-default-rtdb.firebaseio.com',
    storageBucket: 'veterinary-application-bfb4e.appspot.com',
    iosClientId: '1054015406612-8282o0p0f1dr9o7un0m9lahdssscj8v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetCalcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxzKsW3-XWahj_Ba8pq506BaI-jEQj3NQ',
    appId: '1:1054015406612:ios:580775f60e7e206b34dd01',
    messagingSenderId: '1054015406612',
    projectId: 'veterinary-application-bfb4e',
    databaseURL: 'https://veterinary-application-bfb4e-default-rtdb.firebaseio.com',
    storageBucket: 'veterinary-application-bfb4e.appspot.com',
    iosClientId: '1054015406612-8282o0p0f1dr9o7un0m9lahdssscj8v4.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetCalcApp',
  );
}
